#!/bin/bash
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root:" 1>&2
   echo "" 1>&2
   echo "sudo /usr/local/bin/opensc-uninstall" 1>&2
   exit 1
fi

rm -rf /Library/latvia-eid
rm -rf /Applications/otlv-pintool.app
rm -rf /Applications/Latvia-eID-PinTool.app
rm -rf /System/Library/Security/tokend/OTLVID.tokend

for file in /usr/lib/otlv-pkcs11.so /usr/lib/otlv-pkcs11.dylib /usr/local/bin/cardos-tool /usr/local/bin/cryptoflex-tool /usr/local/bin/eidenv /usr/local/bin/netkey-tool /usr/local/bin/opensc-explorer /usr/local/bin/opensc-tool /usr/local/bin/piv-tool /usr/local/bin/pkcs11-tool /usr/local/bin/pkcs15-crypt /usr/local/bin/pkcs15-init /usr/local/bin/pkcs15-tool /usr/local/bin/rutoken-tool /usr/local/bin/westcos-tool; do
	test -L $file && rm -f $file
done
rm -f /usr/local/bin/latvia-eid-uninstall

# delete receipts on 10.6
for file in /var/db/receipts/org.latvia-eid.mac.bom /var/db/receipts/org.latvia-eid.mac.plist; do
	test -f $file && rm -f $file
done

# delete receipts on 10.5
test -d /Library/Receipts/Latvia-eid-middleware_1.0.11-10.5.pkg && rm -rf /Library/Receipts/Latvia-eid-middleware_1.0.11-10.5.pkg

echo "Latvia-eID Middleware has been removed from your system. See you again!"
